const select=document.querySelector('#view'),chart=document.querySelector('#chart'),input=document.querySelector('#search');
const body=document.querySelector('#rows'),detail=document.querySelector('#detail');
for(const v of views){const o=document.createElement('option');o.value=v.id;o.textContent=v.title+' ('+v.count+')';select.append(o)}
const initial=new URL(location.href).searchParams.get('view');
if(views.some(v=>v.id===initial))select.value=initial;
input.value=new URL(location.href).searchParams.get('q')||'';
function current(){return views.find(v=>v.id===select.value)}
function syncLink(){const u=new URL(location.href);u.searchParams.set('view',select.value);input.value.trim()?u.searchParams.set('q',input.value.trim()):u.searchParams.delete('q');u.hash='';document.querySelector('#share').href=u.href;history.replaceState(null,'',u.href)}
function choose(name,scroll=false){const groups=[...chart.querySelectorAll('.institution')];for(const g of groups)g.classList.toggle('selected',g.dataset.name===name);const g=groups.find(g=>g.dataset.name===name);if(g){detail.textContent=g.querySelector('title').textContent;if(scroll)detail.scrollIntoView({behavior:'smooth',block:'center'})}}
function search(){const q=input.value.trim().toLowerCase(),v=current();chart.querySelectorAll('.institution').forEach(g=>g.classList.toggle('dim',!g.dataset.name.toLowerCase().includes(q)));const matches=v.rows.filter(r=>r.name.toLowerCase().includes(q));body.replaceChildren();for(const r of matches){const tr=document.createElement('tr');for(const [i,value] of [r.position,r.name,r.country,r.count].entries()){const td=document.createElement('td');if(i===1){const b=document.createElement('button');b.textContent=value;b.onclick=()=>choose(r.name,true);td.append(b)}else td.textContent=value;if(i===3)td.className='number';tr.append(td)}body.append(tr)}document.querySelector('#matches').textContent=matches.length+' of '+v.count+' shown';document.querySelector('#empty').hidden=matches.length!==0;syncLink()}
function render(){const v=current();chart.innerHTML=v.svg;document.querySelector('#download').href='assets/'+v.id+'.svg';document.querySelector('#download').download=v.filename+'.svg';document.querySelector('#csv').href='data/'+v.id+'.csv';document.querySelector('#csv').download=v.id+'.csv';document.querySelector('#summary').textContent=v.title+' · '+v.count+' institutions';detail.textContent="Click a rectangle to see the institution's full name and paper count.";document.querySelector('#list-title').textContent=v.title+' — full institution names';chart.querySelectorAll('.institution').forEach(g=>{g.setAttribute('tabindex','0');g.setAttribute('role','button');g.setAttribute('aria-label',g.querySelector('title').textContent);g.onclick=()=>choose(g.dataset.name);g.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose(g.dataset.name)}}});search()}
select.onchange=render;input.oninput=search;document.querySelector('#zoom').onchange=e=>chart.style.width=(Number(e.target.value)*100)+'%';document.querySelector('#clear').onclick=()=>{input.value='';search()};render();
